[package]
name = "color_object"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Haneul = { local = "../../../crates/haneul-framework/packages/haneul-framework" }

[addresses]
color_object = "0x0"
