processed 2 tasks

task 1 'publish'. lines 8-15:
Error: Transaction Effects Status: Haneul Move Bytecode Verification Error. Please run the Haneul Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: HaneulMoveVerificationError, source: Some("init function of a module containing one-time witness type candidate must have _::m::M as the first parameter") } }
