processed 3 tasks

task 1 'publish'. lines 8-12:
created: object(103)
written: object(102)

task 2 'publish'. lines 14-19:
Error: Transaction Effects Status: Haneul Move Bytecode Verification Error. Please run the Haneul Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: HaneulMoveVerificationError, source: Some("Expected last (and at most second) parameter for _::n::init to be &mut haneul::tx_context::TxContext; optional first parameter must be of one-time witness type whose name is the same as the capitalized module name: _::n::N") } }
