// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/haneul-open-rpc/spec/openrpc.json
 */

import type { GetCoinsParams } from '@haneullabs/haneul.js/client';
import type { UseHaneulClientQueryOptions } from './useHaneulClientQuery.js';
import { useHaneulClientQuery } from './useHaneulClientQuery.js';

export function useCoins(params: GetCoinsParams, options?: UseHaneulClientQueryOptions<'getCoins'>) {
	return useHaneulClientQuery(
		{
			method: 'getCoins',
			params,
		},
		options,
	);
}
