processed 1 task

task 0 'publish'. lines 6-14:
Error: Transaction Effects Status: Haneul Move Bytecode Verification Error. Please run the Haneul Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: HaneulMoveVerificationError, source: Some("Invalid entry point parameter type. Random must be passed by immutable reference. got: &mut haneul::random::Random"), command: Some(0) } }
