[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/GeunhwaJeong/haneul"
branch = "framework/mainnet"
network = "mainnet"
packages = [
    { path = "crates/haneul-framework/packages/deepbook", watch = "0xdee9" },
    { path = "crates/haneul-framework/packages/move-stdlib", watch = "0x1" },
    { path = "crates/haneul-framework/packages/haneul-framework", watch = "0x2" },
    { path = "crates/haneul-framework/packages/haneul-system", watch = "0x3" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/GeunhwaJeong/haneul"
branch = "framework/testnet"
network = "testnet"
packages = [
    { path = "crates/haneul-framework/packages/deepbook", watch = "0xdee9" },
    { path = "crates/haneul-framework/packages/move-stdlib", watch = "0x1" },
    { path = "crates/haneul-framework/packages/haneul-framework", watch = "0x2" },
    { path = "crates/haneul-framework/packages/haneul-system", watch = "0x3" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/GeunhwaJeong/haneul"
branch = "framework/devnet"
network = "devnet"
packages = [
    { path = "crates/haneul-framework/packages/deepbook", watch = "0xdee9" },
    { path = "crates/haneul-framework/packages/move-stdlib", watch = "0x1" },
    { path = "crates/haneul-framework/packages/haneul-framework", watch = "0x2" },
    { path = "crates/haneul-framework/packages/haneul-system", watch = "0x3" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/GeunhwaJeong/apps"
branch = "main"
network = "mainnet"
packages = [
    { path = "kiosk" },
]

[[packages]]
source = "Repository"
[packages.values]
repository = "https://github.com/GeunhwaJeong/apps"
branch = "testnet"
network = "testnet"
packages = [
    { path = "kiosk" },
]

# [[packages]]
# source = "Repository"
# [packages.values]
# repository = "https://github.com/kunalabs-io/haneul-smart-contracts"
# branch = "master"
# packages = [
#    { path = "kai-finance" }
# ]
