processed 2 tasks

task 0 'publish'. lines 4-11:
Error: Transaction Effects Status: Haneul Move Bytecode Verification Error. Please run the Haneul Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: HaneulMoveVerificationError, source: Some("Expected at least one and at most two parameters for _::m::init") } }

task 1 'publish'. lines 14-21:
Error: Transaction Effects Status: Haneul Move Bytecode Verification Error. Please run the Haneul Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: HaneulMoveVerificationError, source: Some("Expected exactly one parameter for _::m::init  of type &mut haneul::tx_context::TxContext") } }
