error[Haneul E02009]: invalid private transfer call
  ┌─ tests/haneul_mode/private_generics/no_public_transfer.move:8:9
  │
7 │     public fun t1(s: other::S) {
  │                      -------- The type 'a::other::S' is not declared in the current module
8 │         transfer::transfer(s, @0x100);
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'haneul::transfer::transfer' is restricted to being called in the object's module, 'a::other'

error[Haneul E02009]: invalid private transfer call
   ┌─ tests/haneul_mode/private_generics/no_public_transfer.move:12:9
   │
11 │     public fun t2(s: other::S) {
   │                      -------- The type 'a::other::S' is not declared in the current module
12 │         transfer::freeze_object(s);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'haneul::transfer::freeze_object' is restricted to being called in the object's module, 'a::other'

error[Haneul E02009]: invalid private transfer call
   ┌─ tests/haneul_mode/private_generics/no_public_transfer.move:16:9
   │
15 │     public fun t3(s: other::S) {
   │                      -------- The type 'a::other::S' is not declared in the current module
16 │         transfer::share_object(s);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'haneul::transfer::share_object' is restricted to being called in the object's module, 'a::other'

