[package]
name = "Closed Loop Token"
version = "0.0.1"

[dependencies]
Haneul = { git = "https://github.com/GeunhwaJeong/haneul.git", subdir = "crates/haneul-framework/packages/haneul-framework", rev = "framework/testnet" }

[addresses]
closed_loop = "0x0"
examples = "0x0"
