[package]
name = "random_nft"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Haneul = { local = "../../../../crates/haneul-framework/packages/haneul-framework" }

[addresses]
random_nft = "0x0"
