processed 2 tasks

task 1 'publish'. lines 8-15:
Error: Transaction Effects Status: Haneul Move Bytecode Verification Error. Please run the Haneul Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: HaneulMoveVerificationError, source: Some("characteristic type candidate _::m::M must have a single bool field only (or no fields)") } }
