---
version: "3.9"
services:
  haneul-network:
    image: haneullabs/haneul-rosetta-local
    ports:
      - "9000:9000"
    expose:
      - "9000"
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/haneul start
  rosetta-online:
    image: haneullabs/haneul-rosetta-local
    ports:
      - "9002:9002"
    expose:
      - "9002"
    working_dir: /haneul/localnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/haneul-rosetta generate-rosetta-cli-config &
        /usr/local/bin/haneul-rosetta start-online-remote-server --full-node-url http://haneul-network:9000
    stdin_open: true
    tty: true
  rosetta-offline:
    image: haneullabs/haneul-rosetta-local
    ports:
      - "9003:9003"
    expose:
      - "9003"
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/haneul-rosetta start-offline-server