[package]
name = "old-frenemies"
version = "0.0.1"

[dependencies]
Haneul = { local = "../../../crates/haneul-framework/packages/haneul-framework" }
#Haneul = { git = "https://github.com/GeunhwaJeong/haneul.git", subdir = "crates/haneul-framework", rev = "devnet" }

[addresses]
frenemies = "0xac02d650b50456147c2c055c68acac7c545de0a7"
