processed 5 tasks

init:
A: object(100), B: object(101)

task 1 'view-object'. lines 8-8:
Owner: Account Address ( A )
Contents: Haneul::Coin::Coin<Haneul::HANEUL::HANEUL> {id: Haneul::ID::VersionedID {id: Haneul::ID::UniqueID {id: Haneul::ID::ID {bytes: fake(100)}}, version: 0u64}, balance: Haneul::Balance::Balance<Haneul::HANEUL::HANEUL> {value: 100000u64}}

task 2 'run'. lines 10-10:
created: object(105)
written: object(100), object(104)

task 3 'view-object'. lines 12-12:
Owner: Account Address ( A )
Contents: Haneul::Coin::Coin<Haneul::HANEUL::HANEUL> {id: Haneul::ID::VersionedID {id: Haneul::ID::UniqueID {id: Haneul::ID::ID {bytes: fake(100)}}, version: 1u64}, balance: Haneul::Balance::Balance<Haneul::HANEUL::HANEUL> {value: 99990u64}}

task 4 'view-object'. lines 14-14:
Owner: Account Address ( B )
Contents: Haneul::Coin::Coin<Haneul::HANEUL::HANEUL> {id: Haneul::ID::VersionedID {id: Haneul::ID::UniqueID {id: Haneul::ID::ID {bytes: fake(105)}}, version: 1u64}, balance: Haneul::Balance::Balance<Haneul::HANEUL::HANEUL> {value: 10u64}}
