processed 7 tasks

init:
A: object(100), B: object(101), C: object(102)

task 1 'view-object'. lines 8-8:
Owner: Account Address ( B )
Version: 1
Contents: haneul::coin::Coin<haneul::haneul::HANEUL> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(101)}}, balance: haneul::balance::Balance<haneul::haneul::HANEUL> {value: 1000000u64}}

task 2 'run'. lines 10-10:
created: object(107)
written: object(101), object(106)

task 3 'view-object'. lines 12-12:
Owner: Account Address ( B )
Version: 2
Contents: haneul::coin::Coin<haneul::haneul::HANEUL> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(101)}}, balance: haneul::balance::Balance<haneul::haneul::HANEUL> {value: 999990u64}}

task 4 'view-object'. lines 14-14:
Owner: Account Address ( B )
Version: 2
Contents: haneul::coin::Coin<haneul::haneul::HANEUL> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(107)}}, balance: haneul::balance::Balance<haneul::haneul::HANEUL> {value: 10u64}}

task 5 'run'. lines 16-16:
created: object(109)
written: object(101), object(108)

task 6 'view-object'. lines 18-18:
Owner: Account Address ( B )
Version: 3
Contents: haneul::coin::Coin<haneul::haneul::HANEUL> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(101)}}, balance: haneul::balance::Balance<haneul::haneul::HANEUL> {value: 999990u64}}
