---
version: "3.9"
services:
  fullnode:
    image: haneullabs/haneul-node:stable
    ports:
    - "8084:8084/udp"
    - "9000:9000"
    - "9184:9184"
    volumes:
    - ./fullnode-template.yaml:/opt/haneul/config/fullnode.yaml:ro
    - ./genesis.blob:/opt/haneul/config/genesis.blob:ro
    - haneuldb:/opt/haneul/db:rw
    command: ["/opt/haneul/bin/haneul-node", "--config-path", "/opt/haneul/config/fullnode.yaml"]
volumes:
  haneuldb:
