[package]
name = "simple_warrior"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Haneul = { local = "../../../crates/haneul-framework/packages/haneul-framework" }

[addresses]
simple_warrior = "0x0"
