[package]
name = "Tutorial"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../../crates/haneul-framework/deps/move-stdlib/" }
Haneul = { local = "../../../crates/haneul-framework/" }

[addresses]
Tutorial = "0x0"

