[package]
name = "Tutorial"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../../../crates/haneul-framework/packages/move-stdlib/" }
Haneul = { local = "../../../crates/haneul-framework//packages/haneul-framework" }

[addresses]
tutorial = "0x0"
