processed 2 tasks

task 0 'publish'. lines 4-26:
Error: Transaction Effects Status: Haneul Move Bytecode Verification Error. Please run the Haneul Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: HaneulMoveVerificationError, source: Some("Invalid object creation in _::m::foo. Object created without a newly created UID. The UID must come directly from haneul::object::new. Or for tests, it can come from haneul::test_scenario::new_object Found in _::m::foo"), command: Some(0) } }

task 1 'publish'. lines 28-50:
created: object(105)
written: object(104)
