processed 2 tasks

task 0 'publish'. lines 4-36:
Error: Transaction Effects Status: Haneul Move Bytecode Verification Error. Please run the Haneul Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: HaneulMoveVerificationError, source: Some("ID is leaked into a struct. Found in _::test::test"), command: Some(0) } }

task 1 'publish'. lines 38-60:
Error: Transaction Effects Status: Haneul Move Bytecode Verification Error. Please run the Haneul Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: HaneulMoveVerificationError, source: Some("ID is leaked into a struct. Found in _::m::foo"), command: Some(0) } }
