processed 1 task

task 0 'publish'. lines 4-20:
Error: Transaction Effects Status: Haneul Move Bytecode Verification Error. Please run the Haneul Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: HaneulMoveVerificationError, source: Some("Invalid object creation in _::m::foo. Object created without a newly created UID. The UID must come directly from haneul::object::new. Or for tests, it can come from haneul::test_scenario::new_object Found in _::m::foo"), command: Some(0) } }
