processed 7 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-27:
created: object(106)
written: object(105)

task 2 'run'. lines 29-29:
created: object(108)
written: object(107)

task 3 'run'. lines 31-31:
created: object(110), object(111)
written: object(108), object(109)

task 4 'view-object'. lines 33-33:
Owner: Object ID: ( fake(108) )
Version: 3
Contents: haneul::dynamic_field::Field<haneul::dynamic_object_field::Wrapper<u64>, haneul::object::ID> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(110)}}, name: haneul::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: haneul::object::ID {bytes: fake(111)}}

task 5 'transfer-object'. lines 35-35:
Error: Transaction Effects Status: Invalid Transfer Object Transaction. Possibly not address-owned or possibly does not have public transfer.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidTransferObject, source: None, command: None } }

task 6 'view-object'. lines 37-37:
Owner: Object ID: ( fake(108) )
Version: 4
Contents: haneul::dynamic_field::Field<haneul::dynamic_object_field::Wrapper<u64>, haneul::object::ID> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(110)}}, name: haneul::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: haneul::object::ID {bytes: fake(111)}}
