processed 5 tasks

init:
A: object(0,0), B: object(0,1), C: object(0,2)

task 1 'programmable'. lines 8-9:
mutated: object(0,2)

task 2 'view-object'. lines 11-11:
Owner: Account Address ( A )
Version: 2
Contents: haneul::coin::Coin<haneul::haneul::HANEUL> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(0,2)}}, balance: haneul::balance::Balance<haneul::haneul::HANEUL> {value: 299999999986000u64}}

task 3 'transfer-object'. lines 13-13:
mutated: object(0,0), object(0,2)

task 4 'view-object'. lines 15-15:
Owner: Account Address ( B )
Version: 3
Contents: haneul::coin::Coin<haneul::haneul::HANEUL> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(0,2)}}, balance: haneul::balance::Balance<haneul::haneul::HANEUL> {value: 299999999986000u64}}
