processed 4 tasks

init:
A: object(100), B: object(101)

task 1 'view-object'. lines 8-8:
Owner: Account Address ( A )
Version: 0
Contents: haneul::coin::Coin<haneul::haneul::HANEUL> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(100)}}, balance: haneul::balance::Balance<haneul::haneul::HANEUL> {value: 1000000u64}}

task 2 'transfer-object'. lines 10-10:
written: object(100), object(104)

task 3 'view-object'. lines 12-12:
Owner: Account Address ( B )
Version: 1
Contents: haneul::coin::Coin<haneul::haneul::HANEUL> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(100)}}, balance: haneul::balance::Balance<haneul::haneul::HANEUL> {value: 1000000u64}}
