[package]
name = "trusted_swap"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Haneul = { local = "../../../crates/haneul-framework/packages/haneul-framework" }

[addresses]
trusted_swap = "0x0"
