// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/haneul-open-rpc/spec/openrpc.json
 */

import type { GetAllCoinsParams } from '@haneullabs/haneul.js/client';

import type { UseHaneulClientInfiniteQueryOptions } from '../useHaneulClientInfiniteQuery.js';
import { useHaneulClientInfiniteQuery } from '../useHaneulClientInfiniteQuery.js';
import type { UseHaneulClientQueryOptions } from '../useHaneulClientQuery.js';
import { useHaneulClientQuery } from '../useHaneulClientQuery.js';

export function useAllCoins(
	params: GetAllCoinsParams,
	options?: UseHaneulClientQueryOptions<'getAllCoins'>,
) {
	return useHaneulClientQuery(
		{
			method: 'getAllCoins',
			params,
		},
		options,
	);
}

export function useAllCoinsInfinite(
	params: GetAllCoinsParams,
	options?: UseHaneulClientInfiniteQueryOptions<'getAllCoins'>,
) {
	return useHaneulClientInfiniteQuery(
		{
			method: 'getAllCoins',
			params,
		},
		options,
	);
}
