// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/haneul-open-rpc/spec/openrpc.json
 */

import type { DryRunTransactionBlockParams } from '@haneullabs/haneul.js/client';
import type { UseHaneulClientMutationOptions } from '../useHaneulClientMutation.js';
import { useHaneulClientMutation } from '../useHaneulClientMutation.js';

export function useDryRunTransactionBlock(
	params: DryRunTransactionBlockParams,
	options?: UseHaneulClientMutationOptions<'dryRunTransactionBlock'>,
) {
	return useHaneulClientMutation(
		{
			method: 'dryRunTransactionBlock',
			params,
		},
		options,
	);
}
