// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/haneul-open-rpc/spec/openrpc.json
 */

import type { DevInspectTransactionBlockParams } from '@haneullabs/haneul.js/client';
import type { UseHaneulClientMutationOptions } from '../useHaneulClientMutation.js';
import { useHaneulClientMutation } from '../useHaneulClientMutation.js';

export function useDevInspectTransactionBlock(
	params: DevInspectTransactionBlockParams,
	options?: UseHaneulClientMutationOptions<'devInspectTransactionBlock'>,
) {
	return useHaneulClientMutation(
		{
			method: 'devInspectTransactionBlock',
			params,
		},
		options,
	);
}
