// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/haneul-open-rpc/spec/openrpc.json
 */

import type { UseHaneulClientMutationOptions } from '../useHaneulClientMutation.js';
import { useHaneulClientMutation } from '../useHaneulClientMutation.js';

export function useExecuteTransactionBlock(
	options?: UseHaneulClientMutationOptions<'executeTransactionBlock'>,
) {
	return useHaneulClientMutation(
		{
			method: 'executeTransactionBlock',
		},
		options,
	);
}
