// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/haneul-open-rpc/spec/openrpc.json
 */

import type { GetLatestHaneulSystemStateParams } from '@haneullabs/haneul.js/client';

import type { UseHaneulClientQueryOptions } from '../useHaneulClientQuery.js';
import { useHaneulClientQuery } from '../useHaneulClientQuery.js';

export function useLatestHaneulSystemState(
	params: GetLatestHaneulSystemStateParams = {},
	options?: UseHaneulClientQueryOptions<'getLatestHaneulSystemState'>,
) {
	return useHaneulClientQuery(
		{
			method: 'getLatestHaneulSystemState',
			params,
		},
		options,
	);
}
