// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/haneul-open-rpc/spec/openrpc.json
 */

import type { GetOwnedObjectsParams } from '@haneullabs/haneul.js/client';

import type { UseHaneulClientInfiniteQueryOptions } from '../useHaneulClientInfiniteQuery.js';
import { useHaneulClientInfiniteQuery } from '../useHaneulClientInfiniteQuery.js';
import type { UseHaneulClientQueryOptions } from '../useHaneulClientQuery.js';
import { useHaneulClientQuery } from '../useHaneulClientQuery.js';

export function useOwnedObjects(
	params: GetOwnedObjectsParams,
	options?: UseHaneulClientQueryOptions<'getOwnedObjects'>,
) {
	return useHaneulClientQuery(
		{
			method: 'getOwnedObjects',
			params,
		},
		options,
	);
}

export function useOwnedObjectsInfinite(
	params: GetOwnedObjectsParams,
	options?: UseHaneulClientInfiniteQueryOptions<'getOwnedObjects'>,
) {
	return useHaneulClientInfiniteQuery(
		{
			method: 'getOwnedObjects',
			params,
		},
		options,
	);
}
