// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/haneul-open-rpc/spec/openrpc.json
 */

import type { TryGetPastObjectParams } from '@haneullabs/haneul.js/client';

import type { UseHaneulClientQueryOptions } from '../useHaneulClientQuery.js';
import { useHaneulClientQuery } from '../useHaneulClientQuery.js';

export function usePastObject(
	params: TryGetPastObjectParams,
	options?: UseHaneulClientQueryOptions<'tryGetPastObject'>,
) {
	return useHaneulClientQuery(
		{
			method: 'tryGetPastObject',
			params,
		},
		options,
	);
}
