// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/haneul-open-rpc/spec/openrpc.json
 */

import type { QueryEventsParams } from '@haneullabs/haneul.js/client';

import type { UseHaneulClientInfiniteQueryOptions } from '../useHaneulClientInfiniteQuery.js';
import { useHaneulClientInfiniteQuery } from '../useHaneulClientInfiniteQuery.js';
import type { UseHaneulClientQueryOptions } from '../useHaneulClientQuery.js';
import { useHaneulClientQuery } from '../useHaneulClientQuery.js';

export function useQueryEvents(
	params: QueryEventsParams,
	options?: UseHaneulClientQueryOptions<'queryEvents'>,
) {
	return useHaneulClientQuery(
		{
			method: 'queryEvents',
			params,
		},
		options,
	);
}

export function useQueryEventsInfinite(
	params: QueryEventsParams,
	options?: UseHaneulClientInfiniteQueryOptions<'queryEvents'>,
) {
	return useHaneulClientInfiniteQuery(
		{
			method: 'queryEvents',
			params,
		},
		options,
	);
}
