// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 *  ######################################
 *  ### DO NOT EDIT THIS FILE DIRECTLY ###
 *  ######################################
 *
 * This file is generated from:
 * /crates/haneul-open-rpc/spec/openrpc.json
 */

import type { GetReferenceGasPriceParams } from '@haneullabs/haneul.js/client';

import type { UseHaneulClientQueryOptions } from '../useHaneulClientQuery.js';
import { useHaneulClientQuery } from '../useHaneulClientQuery.js';

export function useReferenceGasPrice(
	params: GetReferenceGasPriceParams = {},
	options?: UseHaneulClientQueryOptions<'getReferenceGasPrice'>,
) {
	return useHaneulClientQuery(
		{
			method: 'getReferenceGasPrice',
			params,
		},
		options,
	);
}
