error[Haneul E01001]: invalid object construction
   ┌─ tests/haneul_mode/id_leak/through_pack.move:22:17
   │
22 │         let c = C { id };
   │                 ^^^^^^^^
   │                 │   │
   │                 │   The UID must come directly from haneul::object::new. Or for tests, it can come from haneul::test_scenario::new_object
   │                 Invalid object creation without a newly created UID.

