processed 5 tasks

init:
A: object(103)

task 1 'publish'. lines 8-23:
created: object(105), object(106), object(107)
written: object(104)

task 2 'programmable'. lines 25-27:
created: object(109)
written: object(107), object(108)

task 3 'view-object'. lines 29-29:
Owner: Account Address ( A )
Version: 3
Contents: haneul::coin::Coin<test::fake::FAKE> {id: haneul::object::UID {id: haneul::object::ID {bytes: fake(109)}}, balance: haneul::balance::Balance<test::fake::FAKE> {value: 100u64}}

task 4 'programmable'. lines 31-37:
created: object(111)
written: object(107), object(110)
deleted: object(109)
