[package]
name = "MyFirstPackage"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Haneul = { local = "../../../crates/haneul-framework/packages/haneul-framework" }

[addresses]
my_first_package = "0x0"
