[book]
title = "Haneul Move by Example"
description = "Handy collection of examples for Haneul blockchain, made with love by Haneul Labs."
authors = ["damirka"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/GeunhwaJeong/haneul"
git-repository-icon = "fa-github"
