error[Haneul E02002]: invalid 'entry' function signature
  ┌─ tests/haneul_mode/entry_points/clock_val.move:4:35
  │
4 │     public entry fun no_clock_val(_: haneul::clock::Clock) {
  │            -----                  ^  ----------------- haneul::clock::Clock must be passed by immutable reference, e.g. '&haneul::clock::Clock'
  │            │                      │   
  │            │                      Invalid 'entry' parameter type for parameter '_'
  │            'no_clock_val' was declared 'entry' here

