warning[Lint W03001]: sub-optimal 'haneul::coin::Coin' field type
   ┌─ tests/linter/coin_field.move:11:12
   │
11 │     struct S2 has key, store {
   │            ^^ The field 'c' of 'S2' has type 'haneul::coin::Coin'
12 │         id: UID,
13 │         c: Coin<S1>,
   │         - Storing 'haneul::balance::Balance' in this field will typically be more space-efficient
   │
   = This warning can be suppressed with '#[lint_allow(coin_field)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W03001]: sub-optimal 'haneul::coin::Coin' field type
   ┌─ tests/linter/coin_field.move:25:12
   │
25 │     struct S2 has key, store {
   │            ^^ The field 'c' of 'S2' has type 'haneul::coin::Coin'
26 │         id: UID,
27 │         c: Balance<S1>,
   │         - Storing 'haneul::balance::Balance' in this field will typically be more space-efficient
   │
   = This warning can be suppressed with '#[lint_allow(coin_field)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

