[package]
name = "shared-with-tto"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Haneul = { git = "https://github.com/GeunhwaJeong/haneul.git", subdir = "crates/haneul-framework/packages/haneul-framework", rev = "framework/devnet" }
common = { local = "../common" }

[addresses]
shared_with_tto = "0x0"
