[package]
name = "haneul-capybaras"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
Haneul = { local = "../../../crates/haneul-framework/packages/haneul-framework" }

[addresses]
capy = "0x0"
me = "0x0"
