[package]
name = "BridgedETH"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../../../crates/haneul-framework/packages/move-stdlib" }
Haneul = { local = "../../../../crates/haneul-framework/packages/haneul-framework" }

[addresses]
bridged_eth = "0x0"

