name: Attach Haneul binaries to a release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      haneul_tag:
        description: 'Haneul repo tag to build from'
        type: string
        required: true

env:
  TAG_NAME: "${{ github.event.inputs.haneul_tag || github.ref }}"
  CARGO_TERM_COLOR: always
  # Disable incremental compilation.
  #
  # Incremental compilation is useful as part of an edit-build-test-edit cycle,
  # as it lets the compiler avoid recompiling code that hasn't changed. However,
  # on CI, we're not making small edits; we're almost always building the entire
  # project from scratch. Thus, incremental compilation on CI actually
  # introduces *additional* overhead to support making future builds
  # faster...but no future builds will ever occur in any given CI environment.
  #
  # See https://matklad.github.io/2021/09/04/fast-rust-builds.html#ci-workflow
  # for details.
  CARGO_INCREMENTAL: 0
  # Allow more retries for network requests in cargo (downloading crates) and
  # rustup (installing toolchains). This should help to reduce flaky CI failures
  # from transient network timeouts or other issues.
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  # Don't emit giant backtraces in the CI logs.
  RUST_BACKTRACE: short

jobs:
  release-build:
    timeout-minutes: 80
    strategy:
      matrix:
        os: [ windows-ghcloud, ubuntu-ghcloud, macos-latest-xl, macos-arm64-self-hosted ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # pin@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Clean up tag name ${{ env.TAG_NAME }}
        shell: bash
        run: | 
          echo "haneul_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV

      - name: Checking out ${{ env.haneul_tag }}
        if: ${{ env.haneul_tag != 'main' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ env.haneul_tag }}

      - name: Setup caching
        uses: bmwill/rust-cache@v1 # Fork of 'Swatinem/rust-cache' which allows caching additional paths          
      
      - name: Install nexttest (Windows)
        if: ${{ matrix.os == 'windows-ghcloud' && env.haneul_tag != 'main'  }}
        uses: taiki-e/install-action@nextest

      - name: Setup protoc (Windows)
        if: ${{ matrix.os == 'windows-ghcloud' && env.haneul_tag != 'main'  }}
        uses: arduino/setup-protoc@v1
        # this avoids rate-limiting
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install postgres (Windows)
        if: ${{ matrix.os == 'windows-ghcloud' && env.haneul_tag != 'main'  }}
        shell: bash
        run: |
          choco install postgresql12 --force --params '/Password:root'
          echo "C:\Program Files\PostgreSQL\12\bin" >> $GITHUB_PATH
          echo "C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_PATH
          echo "PQ_LIB_DIR=C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_ENV
          echo "PG_DATABASE_URL=postgres://postgres:root@localhost/" >> $GITHUB_ENV
          echo "PG_EXAMPLE_DATABASE_URL=postgres://postgres:root@localhost/diesel_example" >> $GITHUB_ENV          

      - name: cargo build (release) for ${{ matrix.os }} platform
        if: ${{ env.haneul_tag != 'main' }}
        shell: bash
        run: |
          [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --release
          cd external-crates/move && cargo build -p move-analyzer --release

      - name: Rename binaries for ${{ matrix.os }}
        if: ${{ env.haneul_tag != 'main' && matrix.os != 'windows-ghcloud' }}
        shell: bash
        run: |
          export arch=$(uname -m)
          export system_os=$(echo ${{ matrix.os }} | cut -d- -f1)
          export os_type="${system_os}-${arch}"
          echo "os_type=${system_os}-${arch}" >> $GITHUB_ENV
          mv ./target/release/haneul ./target/release/haneul-${os_type}
          mv ./target/release/haneul-node ./target/release/haneul-node-${os_type}
          mv ./target/release/haneul-tool ./target/release/haneul-tool-${os_type}
          mv ./target/release/haneul-faucet ./target/release/haneul-faucet-${os_type}
          mv ./target/release/haneul-test-validator ./target/release/haneul-test-validator-${os_type}
          mv ./target/release/haneul-indexer ./target/release/haneul-indexer-${os_type}
          mv ./external-crates/move/target/release/move-analyzer ./external-crates/move/target/release/move-analyzer-${os_type}
          tar -cvzf ./target/release/haneul-${{ env.haneul_tag }}-${os_type}.tgz ./target/release/haneul*-${os_type}* ./external-crates/move/target/release/move-analyzer-${os_type}
          [[ ${{ env.haneul_tag }} == *"mainnet"* ]] && aws s3 cp ./target/release/haneul-${{ env.haneul_tag }}-${os_type}.tgz s3://haneul-releases/releases/haneul-${{ env.haneul_tag }}-${os_type}.tgz || true

      - name: Rename binaries for Windows
        if: ${{ env.haneul_tag != 'main' && matrix.os == 'windows-ghcloud' }}
        shell: bash
        run: |
          export arch=$(uname -m)
          export os_type="windows-${arch}"
          echo "os_type=${os_type}" >> $GITHUB_ENV
          mv ./target/release/haneul.exe ./target/release/haneul-${os_type}.exe
          mv ./target/release/haneul-node.exe ./target/release/haneul-node-${os_type}.exe
          mv ./target/release/haneul-tool.exe ./target/release/haneul-tool-${os_type}.exe
          mv ./target/release/haneul-faucet.exe ./target/release/haneul-faucet-${os_type}.exe
          mv ./target/release/haneul-test-validator.exe ./target/release/haneul-test-validator-${os_type}.exe
          mv ./target/release/haneul-indexer.exe ./target/release/haneul-indexer-${os_type}.exe
          mv ./external-crates/move/target/release/move-analyzer.exe ./external-crates/move/target/release/move-analyzer-${os_type}.exe
          tar -cvzf ./target/release/haneul-${{ env.haneul_tag }}-${os_type}.tgz ./target/release/haneul*-${os_type}* ./external-crates/move/target/release/move-analyzer-${os_type}.exe
          [[ ${{ env.haneul_tag }} == *"mainnet"* ]] && aws s3 cp ./target/release/haneul-${{ env.haneul_tag }}-${os_type}.tgz s3://haneul-releases/releases/haneul-${{ env.haneul_tag }}-${os_type}.tgz || true

      - name: Upload release artifacts for ${{ matrix.os }} platform
        if: ${{ env.haneul_tag != 'main' }}
        uses: actions/upload-artifact@v3
        with:
          name: haneul-binaries-${{ matrix.os }}
          if-no-files-found: error
          path: |
            ./target/release/haneul-${{ env.haneul_tag }}-${{ env.os_type }}.tgz

      - name: Publish binaries for ${{ env.haneul_tag }} release
        if: ${{ env.haneul_tag != 'main' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.haneul_tag }}
          files: |
            ./target/release/haneul-${{ env.haneul_tag }}-${{ env.os_type }}.tgz
        env:
          # Have to use a Personal Access Token (PAT), based on https://tinyurl.com/2by2ntdr
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_BUILDS_TOKEN }}
